[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/weather/*"
  to = "https://weather-project-k72v.onrender.com/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[site]
  id = "2371291d-d735-4a0d-a21d-d27affd00377"
